version: 0.2
eb_codebuild_settings:
  CodeBuildServiceRole: codebuild-uwreckcar-codebuild-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: Node.js 16 running on 64bit Amazon Linux 2
  Timeout: 60
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
  artifacts:
    files:
      - '**/*'
    name: uwreckcar-$(date +%Y-%m-%d)